[project]
name = "ZenGardenerBot"
version = "0.1.0"
description = "Bot for Zen garden in PvZ using customtkinter and pyautogui"
authors = ["Valwntwn <lautarovillegas75@gmail.com>"]
dependencies = ["pyautogui==0.9.54", "customtkinter==5.2.2"]
